C89 compatibility in header.c and util.c
Essentially, my perl and/or C toolchain seems to want
to not compile this by default.

  header.c:147:3: error: ‘for’ loop initial declarations are only allowed in C99 mode

This might be because it is a newer GCC (or more likely,
you use clang). Either way, it is probably worth supporting
C89 compilers because otherwise this will not work on Windows.
Sigh.